# Generated by Django 3.0.8 on 2020-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedi',
            name='jedi_position',
            field=models.CharField(choices=[('Y', 'Youngling'), ('P', 'Padawan'), ('K', 'Knight'), ('M', 'Master'), ('W', 'Warrior'), ('S', 'Sage Master'), ('J', 'Jedi Master')], max_length=1),
        ),
    ]
